### PR TITLE
Add method to calculate the width of a String

### PR DESCRIPTION
**Pull request by 3lvis**
# Changelog
- Add method to calculate the width of a String

``` swift
let font = UIFont.systemFont(ofSize: 15)
let greeting = "Good morning, sunshine"
let width = string.width(for: font)
```

### CODE REVIEW

**Comment by 3lvis** [comment]
Is almost Swift 4. Could someone review this one, please?

**Comment by elland** [comment]
¡Barco eso!

**Comment by 3lvis** [comment]
¡Vamos fazer isso!

**Comment by elland** [comment]
@3lvis that doesn't look like spanish 🤔

**Comment by 3lvis** [comment]
@Elland 
brazil-people

**Comment by elland** [comment]
Can I block you on Github? 😄

**Comment by 3lvis** [comment]
@Elland HAHAHA

**Comment by elland** [comment]
@3lvis I think you mean "AUEHHEUAHUAEHUAEHEU" 😢

**Comment by 3lvis** [comment]
@Elland ?

**Comment by elland** [comment]
that's how they laugh :)

**Comment by 3lvis** [comment]
"They" 😂

**Pull request merged**
