### PR TITLE
Add Bounceable protocol

### PR DESCRIPTION
**Pull request by elland**
- To test it, just tap and hold on the collection view cell.

### CODE REVIEW

**Comment by elland** [comment]
Gonna merge this, let me know if there are issues, I'll open a new PR.

**Comment by 3lvis** [comment]
👍

**Comment by elland** [comment]
💃

**Comment by elland** [comment]
@3lvis what do you think of the name? Because it doesn't really bounce, it's more of a wiggle...

**Comment by 3lvis** [comment]
Had a look, definitely not a Bounceable. Maybe shouldn't even be here, seems too specific to be part of a library that you might want to add to every project.

**Comment by elland** [comment]
@3lvis is it? It's the same jiggly effect you have on Springboard to delete apps. Works quite well with collection views. 🤔

**Comment by 3lvis** [comment]
Yeah, I guess we can keep it here for now, if animations grow we'll move it to a different library.

**Comment by 3lvis** [comment]
Maybe the protocol should be called `Jiggling`?

**Comment by elland** [comment]
Jiggly? 💃

**Comment by 3lvis** [comment]
screen shot 2016-11-02 at 10 36 33 am

**Comment by elland** [comment]
Well, problem is `jiggleable` is not a word. `Jiggling` (or any other -ing protocol) makes no sense and should not be there. If they are describing capability with a verb, it should be `Jiggler` (also not word). `Jiggle` is hard to decline.

**Comment by elland** [comment]
I'd go with `Jiggly` because it's a proper real word, describes the property and is clear on intent. Someone should certainly remove the `-ing` suggestion for protocols there.

**Comment by 3lvis** [comment]
Sounds good 👍

**Comment by 3lvis** [comment]
Although I'm still leaning towards `Jiggling`

**Comment by 3lvis** [comment]
😛

**Comment by elland** [comment]
So Jiggly it is? 👯‍♂️

**Pull request merged**
