### PR TITLE
Added watchOS and tvOS support + minor changes

### PR DESCRIPTION
**Pull request by 3lvis**
- Updated renaming where was needed to _UseSweet_
- Added watchOS and tvOS support

### CODE REVIEW

**Comment by elland** [comment]
Mind explaining what this does, why, etc?

**Comment by 3lvis** [comment]
one sec

**Comment by 3lvis** [comment]
@Elland should be more clear now.

**Comment by elland** [comment]
Sounds good to me. 💃 🍌

**Pull request merged**
