### PR TITLE
Reformatted code.

### PR DESCRIPTION
**Pull request by elland**
Swiftformat.

### CODE REVIEW

**Comment by 3lvis** [comment]
This is incorrect if you use Xcode's formatter since indents things inside `#if os(iOS) || os(tvOS)` but I guess it doesn't really matter. shrug

**Review by roberthein — COMMENTED** [review]
👍

**Comment by elland** [comment]
Yeah, it's an option in `SwiftFormat`, I thought we had agreed on that, but we can tweak it!

**Comment by 3lvis** [comment]
@Elland If you can tweak it to do the same as Xcode go for it!

**Comment by 3lvis** [comment]
I would say the ideal formatting is the one that's as close as what Xcode does by default as possible.

**Pull request merged**
