### PR TITLE
UIViewController containment sugar

### PR DESCRIPTION
**Pull request by 3lvis**

### CODE REVIEW

**Comment by elland** [comment]
Can you expand and explain this one?

**Comment by 3lvis** [comment]
@Elland simplifies adding a UIViewController into another UIViewController.

**Comment by elland** [comment]
Why/how? Just by doing all the willAdd/didAdd willRemove/didRemove boilerplate?

**Comment by 3lvis** [comment]
Basically reducing boilerplate and making method calls easier to parse.

**Comment by elland** [comment]
I see. I think `add(controller)` is too small a method signature. `addChild(controller)` perhaps?

**Comment by 3lvis** [comment]
Sounds good!

**Comment by 3lvis** [comment]
Done 👌

**Comment by elland** [comment]
🚀🐑

**Pull request merged**
