### PR TITLE
Feature: less verbose tableView cell dequeue

### PR DESCRIPTION
**Pull request by 3lvis**
``` swift
let cell = tableView.dequeue(TitleCell.self, for: indexPath) as! TitleCell
```

### CODE REVIEW

**Comment by elland** [comment]
@3lvis we can use Generics to make sure that it returns with the correct class type as well. 👍

**Comment by 3lvis** [comment]
@Elland I was thinking on that, but can't make it work. Would serve as a good basis if we manage to do that in the future, though.

**Comment by elland** [comment]
I'll give it a go.

**Comment by 3lvis** [comment]
```swift
let cell = tableView.dequeue(TitleCell(), for: indexPath)
```

**Comment by 3lvis** [comment]
I was able to get to this.

## API

``` swift
let cell = tableView.dequeue(TitleCell(), for: indexPath)
// cell is TitleCell
```

## Implementation

``` swift
public func dequeue<T: UITableViewCell>(_ cellClass: T, for indexPath: IndexPath) -> T {
    return self.dequeueReusableCell(withIdentifier: String(describing: T.self), for: indexPath) as! T
}
```

**Comment by 3lvis** [comment]
That's another suggestion.

**Comment by elland** [comment]
``` swift
let cell = tableView.dequeue(TitleCell.self, for: indexPath)
```

Makes no sense instantiating the class just to pass it along. 👍

**Comment by 3lvis** [comment]
This is gold.

**Comment by elland** [comment]
💃

**Pull request merged**
