### PR TITLE
Add UIScrollView swetness

### PR DESCRIPTION
**Pull request by 3lvis**
## Adds

``` swift
import UIKit

public extension UIScrollView {

    /// A Boolean value that indicates whether the scrollView's contentOffset is located at the top.
    public var isAtTheTop: Bool { get }

    /// A Boolean value that indicates whether the scrollView's contentOffset is located at the bottom.
    public var isAtTheBottom: Bool { get }
}
```

### CODE REVIEW

**Comment by elland** [comment]
@3lvis Mind testing this with really really massive scrollviews full of content? Over 20k height?

**Comment by 3lvis** [comment]
@Elland have anything specific in mind? That might require some UI tests.

**Comment by 3lvis** [comment]
https://github.com/UseSweet/SweetUIKit/issues/34

**Comment by elland** [comment]
What do you mean by something specific in mind? The reason I ask is because AFAIK scrollviews (since iOS7, at least) have been absurdly unreliable at giving you accurate content sizes after a certain size threshold.

**Comment by 3lvis** [comment]
> have anything specific in mind

You gave a good answer to that. That's exactly what I meant. Would be nice to see how that works.

**Pull request merged**
