### PR TITLE
Add completion block for error alert

### PR DESCRIPTION
**Pull request by elland**

### CODE REVIEW

**Comment by 3lvis** [comment]
Maybe `dismissedBlock` would be a better name for the closure?

**Comment by 3lvis** [comment]
@Elland what's the use case for this again? What would you do when this gets dismissed?

**Comment by elland** [comment]
@3lvis simplest example I have: you want to dismiss a view controller in case of error, or you want to change application state.

**Comment by 3lvis** [comment]
Could you be more specific please? What are you using this for right now? Just trying to keep the source as simple as possible :)

**Comment by elland** [comment]
@3lvis I was, for the action extension for Pinboard. 👍

**Comment by 3lvis** [comment]
Since it's open source, could you link where you're using it?

**Comment by elland** [comment]
@3lvis _I was_ using it. 😢

**Comment by elland** [comment]
Thought I'd open a request anyway, as to avoid waiting for one in the future if I need again. 👍

**Comment by 3lvis** [comment]
Haha, seems like is not needed anymore.

Let's try to not keep code around that we're not using. If you find some more that we're not using please shot out.

**Comment by elland** [comment]
😢

**Pull request closed without merging**
