### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by elland**

### CODE REVIEW

**Comment by 3lvis** [comment]
The toad doesn't become Cinderella, it becomes the prince.

**Comment by elland** [comment]
Yeah, but it doesn't need to make sense. Also the toad doesn't become Cinderella's prince either. 😄

**Comment by 3lvis** [comment]
Hahaha, let's find another analogy.

**Comment by 3lvis** [comment]
Screw it, let's drop the analogy.

**Comment by 3lvis** [comment]
https://github.com/UseSweet/SweetUIKit/blob/master/README.md

**Comment by 3lvis** [comment]
Removed analogy

**Pull request closed without merging**
