### PR TITLE
Update height method

### PR DESCRIPTION
**Pull request by marijnschilling**
Infer the width from the label's current frame

### CODE REVIEW

**Comment by 3lvis** [comment]
Hi @marijnschilling!

Could you check the tests, please? Looks like they are failing. 😁 

screen shot 2016-12-15 at 4 57 47 pm

**Comment by marijnschilling** [comment]
They all succeed though!
screenshot 2016-12-15 17 06 22
screenshot 2016-12-15 17 06 02

**Comment by 3lvis** [comment]
@marijnschilling Looks like they are failing for the tvOS target.

**Comment by marijnschilling** [comment]
@Elvis i don't really get those test why are they different in the first place? 
❓
🤔

**Comment by 3lvis** [comment]
@marijnschilling They are the same tests, but the results can be different.

**Comment by marijnschilling** [comment]
Hmmm but i don't understand how the results can be different, why is the width of a string "a" different on apple tv?

**Comment by 3lvis** [comment]
@marijnschilling Probably they tweaked the implementation so it fits better what they do in a wide-screen? I really don't know 🙃

**Comment by marijnschilling** [comment]
oke fixed the test, but don't really know why it's different

**Comment by 3lvis** [comment]
👏

**Review by 3lvis — COMMENTED** [review]
Sweet!

**Pull request merged**
