### PR TITLE
Add IndexPath helpers

### PR DESCRIPTION
**Pull request by 3lvis**

### CODE REVIEW

**Comment by elland** [comment]
Isn't this a Foundation class? 💭

**Comment by 3lvis** [comment]
It was, now is not :D Swift 3 made it a value type

**Comment by elland** [comment]
So, SweetSwift? 😛

**Comment by 3lvis** [comment]
Pretty much if it doesn't need `NS` then it's a value type.

**Comment by 3lvis** [comment]
This specific extensions require UITableView and UICollectionView, so you need to import UIKit.

**Comment by elland** [comment]
I'm convinced. 🚢 it!

**Pull request merged**
