### PR TITLE
Updated to Swift4 and Xcode 9.

### PR DESCRIPTION
**Pull request by elland**

### CODE REVIEW

**Comment by 3lvis** [comment]
Already!?

**Comment by 3lvis** [comment]
I guess this could have been the only thing stopping us:

https://twitter.com/circleci/status/908025845947678720

**Comment by elland** [comment]
Possible, checking!

**Comment by elland** [comment]
@3lvis actually the string width calculation result changed.

**Review by 3lvis — APPROVED** [review]

**Comment by 3lvis** [comment]
🔥 👍 🔥

**Comment by elland** [comment]
Did we tag it? 👍

**Comment by 3lvis** [comment]
No tag until it's production ready. Please use master for now.

**Pull request merged**
