### PR TITLE
Remove separator from tableviews

### PR DESCRIPTION
**Pull request by elland**
- Table view should not be responsible for cell design.

### CODE REVIEW

**Comment by elland** [comment]
Merging now so I can move on with work. 🙆

**Comment by 3lvis** [comment]
Sounds like something project specific. Could you move this change to your project instead?

**Comment by elland** [comment]
No, this is architecture. Having the tableview be responsible for drawing the cell separator makes no sense. This should've been deprecated years ago, certainly legacy from iPhoneOS still.

**Comment by 3lvis** [comment]
I would understand if a lot of people could disagree with you, including @marijnschilling and me. Please roll back.

**Comment by elland** [comment]
I don't understand what you mean. 🤔

**Comment by 3lvis** [comment]
I'm saying that this is not a good default. And that we should roll back since @marijnschilling and me don't agree with this.

simulator screen shot nov 2 2016 1 13 04 pm

**Comment by 3lvis** [comment]
Since this is a change that needs some discussion, I'm going to roll it back so we can discuss it properly.

**Comment by marijnschilling** [comment]
Where we will discuss it? Here? I have arguments up my sleeve

**Comment by elland** [comment]
Here is fine, for posterity. I agree that it's an ugly default, but it is the default. Having the tableview have separators make absolutely no sense to me, it's such a clear violation of responsibilities, but go on.

**Comment by marijnschilling** [comment]
I think tableView should be responsible for separators because separators say something about how the cells _relate_ to eachother (i.e: last cell doesnt show separator etc.) It's not something a cell can decide for itself.

**Comment by elland** [comment]
> last cell doesnt show separator
1. The iOS default has separators even when there are no cells.
2. Since when? Also you can tell the cell to show or not show an element based on arbitrary logic. Telling what it should display should come from the model/controller, actually laying it out shouldn't. It's the equivalent of having the table view controller setting the cell's title label colour. It's leaking. 🤔

**Comment by 3lvis** [comment]
You're proposing to draw the separators inside the cells instead, @Elland?

**Comment by elland** [comment]
Where else would you draw a cell subview? They're not cell separators, they are decoration inside the cell.

**Comment by elland** [comment]
This shows more clearly when you need a decorator that is not supported by the tableview out of the box. Do you subclass the tableview to override the separator drawing or do you set it to `.none` and add a separator subview to the cell? 🤔

**Pull request merged**
