### PR TITLE
Add auto-layout convenience initialiser

### PR DESCRIPTION
**Pull request by elland**
Simpler.

### CODE REVIEW

**Comment by 3lvis** [comment]
Why not including it in the previous extension?

**Comment by elland** [comment]
:dolan:

**Comment by 3lvis** [comment]
screen shot 2016-08-29 at 13 48 21

**Comment by elland** [comment]
Dolan recursion.

**Comment by 3lvis** [comment]
Good addition. 👏

**Comment by elland** [comment]
👍

**Pull request merged**
