### PR TITLE
Add OpenInSafariActivity, remove app-extension safety for now

### PR DESCRIPTION
**Pull request by elland**
Also added it to the Demo app, so we can see how the localisation fallback chain works. 🆗

### CODE REVIEW

**Comment by 3lvis** [comment]
How come this is not there by default. 😱 Gonna run it in my phone, one sec.

**Comment by elland** [comment]
Right?!

**Comment by 3lvis** [comment]
Great addition, @Elland.

**Comment by elland** [comment]
💃

**Pull request merged**
